name = "nebulai-backend"
main = "src/index.ts"
compatibility_date = "2024-11-11"

compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "PROMPTS"
id = "${PROMPTS_NAMESPACE_ID}"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[ d1_databases ]]
binding = "DB"
database_name = "nebulai-backend-db"
database_id = "906d822f-252b-458a-81b4-8272f2611604"
migrations_dir = "./src/db/migrations"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1